name: CI build

on:
  push:
    branches: [master, release, gh_actions*]
  pull_request:
  release:
    types:
      - created

permissions:
  contents: write

jobs:
  build_msvc:
    name: "Windows MSVC: ${{ matrix.toolset }} ${{ matrix.msvc_arch }} ${{ matrix.run_unit_test && '+Test' }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:

          - toolset: v143
            os: windows-latest
            msvc_arch: x64

    steps:
      - uses: actions/checkout@v4

      - name: Static build
        run: |
          $ErrorActionPreference = 'stop'
          $PSNativeCommandUseErrorActionPreference = $true
          cmake -S . -B build/static -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=0 -A "${{ matrix.msvc_arch }}" -T "${{ matrix.toolset }}"
          cmake --build build/static --config Release

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-binaries-${{ matrix.toolset }}-${{ matrix.msvc_arch }}
          path: build/static/Release/*.exe

  
